### ISSUE TITLE
Update READ.ME

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/auk-notebooks#23]
Opening a ticket to discuss content on READ.me. I've made some adjustments, which I think if rest of team agrees, can be implemented once we're ready. The other part of this ticket brings up some discussion points, things to consider reworking in this document. 

# Updates to READ.me

- [x] list Docker and Anaconda Distribution under Requirements with note
- [x] insert URLs for each requirement

# Instruction Testing (Results)

* Installing requirements wasn't as painful as I thought it would be; adding in URLs for individuals to go to cut down time 
* Docker Hub worked beautifully!
* Docker Locally - bash commands were successful, but I had no idea what to do after this. 

# Additional Notes

* In the requirements section, short description on why Docker/Anaconda are suggestions (they are...)
* Think about order of Docker and Anaconda
* I think we need to add a bit of a description within Docker / Anaconda section; right now it flows as if you have to do one and then the other. Is there a reason to choose Docker over Anaconda (e.g. local environment)? or perhaps a short paragraph can be added under the usage header. 
* when I was installing Python, wondering if we need to also attend to Certifi: https://pypi.org/project/certifi/
* once we get a bit further with testing, copyediting, and other PRs should update READ.me to include notebook walk through? or at very least a short paragraph that lists overview of what you can do with notebook and one screenshot.

**Comment by ianmilligan1** [comment]
This sounds really promising, @SamFritz! Some thoughts on the above:

- Docker locally: you need to paste the token into a URL. i.e. we could suggest they type `127.0.0.1:8888/` into their browser and then add the `?token=xxxx` string. For example, on my run through, the URL was 127.0.0.1:8888/?token=65ed5b980e753adf4478a41001d3391261f04217248b45b6
- Docker/Anaconda rationale: Docker is a container-based virtual machine system (@ruebot might word this better) that can let us bundle all the dependencies together. So you can build the docker image and it will work out of the box. Anaconda is a package manager that can help you find packages and dependencies, including some of the most popular data science ones.
- Let's do Anaconda first then Docker.
- Docker might be good for trying things out; Anaconda will be slightly easier for working with your own data? 
- No clue on Certifi. I don't _think_ we need to mention it?
- Yes, maybe a few bullet points of what you can do there.

I think we can start a README.md branch and then begin to implement above.

**Comment by SamFritz** [comment]
Issue was closed with [PR #34](https://github.com/archivesunleashed/auk-notebooks/pull/34)
